apiVersion: v1
kind: Secret
metadata:
  name: budget-app-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo
type: Opaque
stringData:
  url: git@github.com:YOUR_USERNAME/budget-app-k8s.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    YOUR-GENERATED-PRIVATE-KEY-HERE
    -----END OPENSSH PRIVATE KEY-----
